import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const featured = searchParams.get("featured");
  
  // Simulate network latency
  await new Promise((resolve) => setTimeout(resolve, 800));

  const projects = [
  {
    id: "SNC-015",
    title: "6400sqm Warehouse",
    client: "Mega Market",
    sector: "Industrial Infrastructure",
    status: "Completed",
    budget: "Confidential",
    duration: "14 months",
    scope: "Steel portal frame, structural envelope, and civils",
    image: "/snc_industrial_warehouse.png",
    grid: "lg:col-span-7 lg:row-span-2",
  },
  {
    id: "SNC-014",
    title: "Container Stacking Pad",
    client: "Africa University",
    sector: "Civil Infrastructure",
    status: "Completed",
    budget: "Confidential",
    duration: "8 months",
    scope: "Heavy duty concrete paving and groundworks",
    image: "/snc_civil_yard.png",
    grid: "lg:col-span-5 lg:row-span-1",
  },
  {
    id: "SNC-013",
    title: "Office Block Extension",
    client: "Mega Market",
    sector: "Commercial Construction",
    status: "Completed",
    budget: "Confidential",
    duration: "12 months",
    scope: "Multi-story concrete frame and finishing",
    image: "/snc_commercial_office.png",
    grid: "lg:col-span-5 lg:row-span-1",
  },
  {
    id: "SNC-012",
    title: "Wheat Mill Civils",
    client: "Mega Market",
    sector: "Industrial Engineering",
    status: "Completed",
    budget: "Confidential",
    duration: "10 months",
    scope: "Complex civil works for milling plant",
    image: "/proj-earthworks.jpg",
    grid: "lg:col-span-4 lg:row-span-1",
  },
  {
    id: "SNC-011",
    title: "Transport Yard",
    client: "Mega Market",
    sector: "Civil Paving",
    status: "Completed",
    budget: "Confidential",
    duration: "6 months",
    scope: "Heavy haulage surface preparation",
    image: "/proj-highway.jpg",
    grid: "lg:col-span-4 lg:row-span-1",
  },
  {
    id: "SNC-010",
    title: "Hotel Renovations",
    client: "Troutbeck Resort",
    sector: "Hospitality Renovation",
    status: "Completed",
    budget: "Confidential",
    duration: "18 months",
    scope: "Structural upgrades and luxury finishing",
    image: "/proj-commercial.jpg",
    grid: "lg:col-span-4 lg:row-span-1",
  },
  {
    id: "SNC-009",
    title: "Maize Milling Project",
    client: "Mega Market",
    sector: "Industrial Plant",
    status: "Completed",
    budget: "Confidential",
    duration: "11 months",
    scope: "Plant construction and silo foundations",
    image: "/proj-mining.jpg",
    grid: "lg:col-span-6 lg:row-span-1",
  },
  {
    id: "SNC-008",
    title: "4500sqm Warehouse",
    client: "Mega Market",
    sector: "Industrial Infrastructure",
    status: "Completed",
    budget: "Confidential",
    duration: "9 months",
    scope: "Warehouse structure and polished concrete flooring",
    image: "/snc_industrial_warehouse.png",
    grid: "lg:col-span-6 lg:row-span-1",
  },
  {
    id: "SNC-007",
    title: "Boys Hostel Block",
    client: "Hillcrest Schools",
    sector: "Institutional Buildings",
    status: "Completed",
    budget: "Confidential",
    duration: "14 months",
    scope: "Multi-level residential block construction",
    image: "/proj-commercial.jpg",
    grid: "lg:col-span-3 lg:row-span-1",
  },
  {
    id: "SNC-006",
    title: "Lower Transport Yard",
    client: "Mega Market",
    sector: "Civil Infrastructure",
    status: "Completed",
    budget: "Confidential",
    duration: "5 months",
    scope: "Logistics yard paving",
    image: "/proj-highway.jpg",
    grid: "lg:col-span-5 lg:row-span-1",
  },
  {
    id: "SNC-005",
    title: "Dining Hall Renovations",
    client: "St Charles Lwanga",
    sector: "Institutional Renovation",
    status: "Completed",
    budget: "Confidential",
    duration: "4 months",
    scope: "Refurbishment and structural repair",
    image: "/snc_commercial_office.png",
    grid: "lg:col-span-4 lg:row-span-1",
  },
  {
    id: "SNC-004",
    title: "Concrete Paving Dry Port",
    client: "GMS Dry Port",
    sector: "Civil Infrastructure",
    status: "Completed",
    budget: "Confidential",
    duration: "10 months",
    scope: "Extensive concrete paving for dry port operations",
    image: "/snc_civil_yard.png",
    grid: "lg:col-span-8 lg:row-span-1",
  },
  {
    id: "SNC-003",
    title: "Residents Units",
    client: "Eastern Highlands Trust",
    sector: "Residential Development",
    status: "Completed",
    budget: "Confidential",
    duration: "16 months",
    scope: "Turnkey residential construction",
    image: "/proj-commercial.jpg",
    grid: "lg:col-span-4 lg:row-span-1",
  },
  {
    id: "SNC-002",
    title: "Pie Shop Renovation",
    client: "Surrey Mutare Depot",
    sector: "Commercial Renovation",
    status: "Completed",
    budget: "Confidential",
    duration: "3 months",
    scope: "Retail space fit-out and refurbishment",
    image: "/snc_commercial_office.png",
    grid: "lg:col-span-5 lg:row-span-1",
  },
  {
    id: "SNC-001",
    title: "Pallet Shade",
    client: "Mega Market",
    sector: "Industrial Infrastructure",
    status: "Completed",
    budget: "Confidential",
    duration: "2 months",
    scope: "Steel shade structure",
    image: "/proj-bridge.jpg",
    grid: "lg:col-span-7 lg:row-span-1",
  }
];

  return NextResponse.json({
    status: "success",
    data: featured === "true" ? projects : projects,
  });
}
