-- 254: evaluate session lookups once per query in row-level security (stress test 2026-10-07).
--
-- 175 policies called current_setting(...) / auth.uid() directly in their
-- USING / WITH CHECK expressions, so Postgres re-evaluated them for every
-- row scanned (Supabase advisor: auth_rls_initplan). Wrapping each call in
-- (SELECT ...) lets the planner evaluate it once per statement as an
-- InitPlan. The result is identical - these functions are stable within a
-- statement - only the cost changes.
--
-- Generated from pg_policies; each ALTER POLICY keeps the policy's existing
-- roles and command and only replaces its expressions.

ALTER POLICY "compliance_project_scope" ON "compliance"."applicability_assessments" USING ((((SELECT current_setting('app.compliance_all'::text, true)) = 'true'::text) OR ((project_id IS NULL) AND (created_by = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid)) OR (EXISTS ( SELECT 1
   FROM compliance.scope_grants g
  WHERE ((g.organization_id = applicability_assessments.organization_id) AND (g.project_id = applicability_assessments.project_id) AND (g.user_id = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid)))))) WITH CHECK ((((SELECT current_setting('app.compliance_all'::text, true)) = 'true'::text) OR ((project_id IS NULL) AND (created_by = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid)) OR (EXISTS ( SELECT 1
   FROM compliance.scope_grants g
  WHERE ((g.organization_id = applicability_assessments.organization_id) AND (g.project_id = applicability_assessments.project_id) AND (g.user_id = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid))))));
ALTER POLICY "compliance_tenant" ON "compliance"."applicability_assessments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_project_scope" ON "compliance"."assignments" USING ((((SELECT current_setting('app.compliance_all'::text, true)) = 'true'::text) OR ((project_id IS NULL) AND (created_by = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid)) OR (EXISTS ( SELECT 1
   FROM compliance.scope_grants g
  WHERE ((g.organization_id = assignments.organization_id) AND (g.project_id = assignments.project_id) AND (g.user_id = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid)))))) WITH CHECK ((((SELECT current_setting('app.compliance_all'::text, true)) = 'true'::text) OR ((project_id IS NULL) AND (created_by = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid)) OR (EXISTS ( SELECT 1
   FROM compliance.scope_grants g
  WHERE ((g.organization_id = assignments.organization_id) AND (g.project_id = assignments.project_id) AND (g.user_id = (NULLIF((SELECT current_setting('request.jwt.claim.sub'::text, true)), ''::text))::uuid))))));
ALTER POLICY "compliance_tenant" ON "compliance"."assignments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_tenant" ON "compliance"."authorities" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_tenant" ON "compliance"."domains" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_tenant" ON "compliance"."obligation_versions" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_tenant" ON "compliance"."obligations" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_tenant" ON "compliance"."scope_grants" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_tenant" ON "compliance"."sources" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."approval_decisions" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."approval_decisions" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."approval_instances" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."approval_instances" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."approval_steps" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."approval_steps" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."audit_log" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."audit_log" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."command_receipts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."command_receipts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "core"."compliance_items" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "core"."documents" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "core"."documents" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."documents" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."domain_events" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."domain_events" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."event_dispatch_attempts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."event_dispatch_attempts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "core"."event_receipts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."event_receipts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "core"."file_attachments" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "core"."file_attachments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."file_attachments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "core"."internal_messages" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "core"."notifications" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "compliance_notification_fence" ON "core"."notifications" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_notification_tenant" ON "core"."notifications" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Global Write Policy" ON "core"."permissions" USING (((SELECT current_setting('role'::text)) = 'service_role'::text));
ALTER POLICY "PWA subscriptions owner delete" ON "core"."pwa_push_subscriptions" USING ((user_id = ((SELECT current_setting('request.jwt.claim.sub'::text, true)))::uuid));
ALTER POLICY "PWA subscriptions owner read" ON "core"."pwa_push_subscriptions" USING ((user_id = ((SELECT current_setting('request.jwt.claim.sub'::text, true)))::uuid));
ALTER POLICY "PWA subscriptions owner write" ON "core"."pwa_push_subscriptions" WITH CHECK ((user_id = ((SELECT current_setting('request.jwt.claim.sub'::text, true)))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "core"."roles" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Global Write Policy" ON "core"."system_modules" USING (((SELECT current_setting('role'::text)) = 'service_role'::text));
ALTER POLICY "Tenant Isolation Policy" ON "core"."user_roles" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "core"."users" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "core"."users" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "core"."users" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."accountability_targets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."activities" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."automation_rules" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."automation_runs" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."campaign_members" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."campaigns" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."communication_events" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."contacts" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."interactions" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."leads" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."message_templates" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."nurture_sequences" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."opportunities" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."organizations" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."pipeline_stages" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."segments" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."sequence_steps" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."sla_policies" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."subcontractors" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "compliance_master_fence" ON "crm"."subcontractors" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_master_tenant" ON "crm"."subcontractors" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."support_tickets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."tender_interests" USING (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."tenders" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."ticket_comments" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."ticket_sla_events" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."tickets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."web_intakes" USING (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."website_enquiries" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "crm"."win_loss_reasons" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "executive"."automated_reports" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "executive"."bi_reports" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "executive"."dashboards" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "executive"."kpi_metrics" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "executive"."kpi_snapshots" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "executive"."risk_register" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "finance"."budgets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "finance"."departments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "finance"."departments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "finance"."financial_performance" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "finance"."quotations" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "fleet"."equipment_assets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "fleet"."fleet" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "compliance_master_fence" ON "fleet"."fleet" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_master_tenant" ON "fleet"."fleet" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "fleet"."maintenance_schedules" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "hr"."applications" USING (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employee_asset_assignments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_asset_assignments" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employee_availability" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_availability" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employee_certifications" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_certifications" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_contracts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employee_documents" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_documents" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employee_medicals" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_medicals" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_psychometrics" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employee_skills" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employee_skills" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "hr"."employees" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "hr"."employees" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."employees" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."expiry_alerts" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."leave_requests" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."leave_requests" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."positions" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."positions" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."project_allocations" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."project_allocations" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."public_holidays" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "hr"."records" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "workforce_runtime_fence" ON "hr"."reporting_lines" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."reporting_lines" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."training_records" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."training_records" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."training_requirements" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."training_requirements" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."weekly_hours" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."worker_categories" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."worker_categories" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_fence" ON "hr"."worker_engagements" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "workforce_runtime_tenant" ON "hr"."worker_engagements" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid)) WITH CHECK ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "procurement"."inventory_items" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "procurement"."suppliers" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "compliance_master_fence" ON "procurement"."suppliers" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_master_tenant" ON "procurement"."suppliers" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "projects"."hse_incidents" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "projects"."projects" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "compliance_master_fence" ON "projects"."projects" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "compliance_master_tenant" ON "projects"."projects" USING ((organization_id = (NULLIF((SELECT current_setting('app.organization_id'::text, true)), ''::text))::uuid));
ALTER POLICY "Tenant Isolation Policy" ON "projects"."site_operations" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text))) WITH CHECK (((organization_id = ( SELECT get_jwt_org_id() AS get_jwt_org_id)) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Global Read Policy" ON "public"."audit_log" USING ((((SELECT current_setting('role'::text)) = 'service_role'::text) OR true));
ALTER POLICY "Global Write Policy" ON "public"."audit_log" USING (((SELECT current_setting('role'::text)) = 'service_role'::text));
ALTER POLICY "Tenant Isolation Policy" ON "public"."automated_reports" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."bi_reports" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."budgets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."client_portal_tickets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."compliance_items" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."crm_contacts" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."crm_leads" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."documents" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."equipment_assets" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."file_attachments" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."financial_performance" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."fleet" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."hr_records" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."hse_incidents" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."internal_messages" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."inventory_items" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."kpi_metrics" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."maintenance_schedules" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."notifications" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Global Write Policy" ON "public"."permissions" USING (((SELECT current_setting('role'::text)) = 'service_role'::text));
ALTER POLICY "Tenant Isolation Policy" ON "public"."procurement_orders" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."projects" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."quotations" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."risk_register" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."roles" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."site_operations" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."supplier_records" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Global Write Policy" ON "public"."system_modules" USING (((SELECT current_setting('role'::text)) = 'service_role'::text));
ALTER POLICY "Tenant Isolation Policy" ON "public"."tender_bids" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."user_roles" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."users" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."website_enquiries" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
ALTER POLICY "Tenant Isolation Policy" ON "public"."workforce" USING (((organization_id = get_jwt_org_id()) OR ((SELECT current_setting('role'::text)) = 'service_role'::text)));
